### ISSUE TITLE
Auto closes on drag n drop and entering Start! .

### ISSUE THREAD

**Issue by TrickPixeltje** [xsilent007/Loki#1]
Hello, The program will automatically close on dragndrop, And when I press Start! Manually, It also just auto closes??

**Comment by xsilent007** [comment]
What settings are you using?

**Comment by TrickPixeltje** [comment]
WOops, I figured out it's just the obfuscation fucking it over. Sorry!
It auto closed because of the obfuscation and because i had apache running on localhost 😂
